### Creates a new patient entity
###POST http://localhost:4004/api/patients
POST http://lb-551ccfc0.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe Kafka2 Test",
  "email": "kafka_test13@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###